// <auto-generated />
namespace Goplecs.GTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedPhotocolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPhotocolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201712241644076_addedPhotocolumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
